=== io7m-com/certusine/com.io7m.certusine.vanilla/src/main/resources/com/io7m/certusine/vanilla/internal/config-1.schema.json
{
  "$id": "https://www.io7m.com/software/certusine/config-1.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",

  "$defs": {
    "SchemaIdentifier": {
      "type": "string",
      "const": "https://www.io7m.com/software/certusine/config-1.json"
    },

    "Parameter": {
      "type": "object",
      "properties": {
        "Name": {
          "type": "string"
        },
        "Value": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "Name",
        "Value"
      ]
    },

    "Output": {
      "type": "object",
      "properties": {
        "Type": {
          "type": "string"
        },
        "Name": {
          "type": "string"
        },
        "Parameters": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Parameter"
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "Type",
        "Name",
        "Parameters"
      ]
    },

    "DNSConfigurator": {
      "type": "object",
      "properties": {
        "Type": {
          "type": "string"
        },
        "Name": {
          "type": "string"
        },
        "Parameters": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Parameter"
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "Type",
        "Name",
        "Parameters"
      ]
    },

    "Account": {
      "type": "object",
      "properties": {
        "Name": {
          "type": "string"
        },
        "PublicKeyPath": {
          "type": "string"
        },
        "PrivateKeyPath": {
          "type": "string"
        },
        "AcmeURI": {
          "type": "string",
          "format": "uri"
        }
      },
      "additionalProperties": false,
      "required": [
        "Name",
        "PublicKeyPath",
        "PrivateKeyPath",
        "AcmeURI"
      ]
    },

    "Certificate": {
      "type": "object",
      "properties": {
        "Name": {
          "type": "string",
          "pattern": "[a-z0-9]([a-z0-9\\._-]*)"
        },
        "Hosts": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "PublicKeyPath": {
          "type": "string"
        },
        "PrivateKeyPath": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "Name",
        "Hosts",
        "PublicKeyPath",
        "PrivateKeyPath"
      ]
    },

    "Domain": {
      "type": "object",
      "properties": {
        "Name": {
          "type": "string"
        },
        "Account": {
          "type": "string"
        },
        "Certificates": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Certificate"
          }
        },
        "Outputs": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "DNSConfigurator": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "Account",
        "Certificates",
        "DNSConfigurator",
        "Name",
        "Outputs"
      ]
    },

    "Options": {
      "type": "object",
      "properties": {
        "DNSWaitTime": {
          "type": "string"
        },
        "CertificateStore": {
          "type": "string"
        },
        "CertificateExpirationThreshold": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "CertificateStore"
      ]
    },

    "Configuration": {
      "type": "object",
      "properties": {
        "%Schema": {
          "$ref": "#/$defs/SchemaIdentifier"
        },
        "Accounts": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Account"
          }
        },
        "Outputs": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Output"
          }
        },
        "DNSConfigurators": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/DNSConfigurator"
          }
        },
        "Domains": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Domain"
          }
        },
        "Options": {
          "$ref": "#/$defs/Options"
        }
      },
      "additionalProperties": false,
      "required": [
        "%Schema",
        "Outputs",
        "DNSConfigurators",
        "Domains",
        "Options"
      ]
    }
  },

  "$ref": "#/$defs/Configuration"
}

=== io7m-com/certusine/com.io7m.certusine.documentation/src/main/resources/com/io7m/certusine/documentation/config.json
{
  "%Schema": "https://www.io7m.com/software/certusine/config-1.json",

  "Options": {
    "DNSWaitTime": "PT5M",
    "CertificateStore": "store.db",
    "CertificateExpirationThreshold": "PT72H"
  },

  "Accounts": [
    {
      "Name": "main",
      "PublicKeyPath": "account.pub",
      "PrivateKeyPath": "account.pri",
      "AcmeURI": "https://acme-staging-v02.api.letsencrypt.org/directory"
    }
  ],

  "Outputs": [
    {
      "Type": "directory",
      "Name": "main-output",
      "Parameters": [
        {
          "Name": "path",
          "Value": "/tmp"
        }
      ]
    }
  ],

  "DNSConfigurators": [
    {
      "Type": "vultr",
      "Name": "vultr-dns",
      "Parameters": [
        {
          "Name": "api-key",
          "Value": "25DDk6MT+2JI5KBABMysYLPFEOge+MZE3/GiBgrR+CU="
        },
        {
          "Name": "domain",
          "Value": "example.com"
        }
      ]
    }
  ],

  "Domains": [
    {
      "Name": "example.com",
      "Account": "main",
      "Certificates": [
        {
          "Name": "www",
          "PublicKeyPath": "www.pub",
          "PrivateKeyPath": "www.pri",
          "Hosts": [
            "www.example.com"
          ]
        }
      ],
      "Outputs": [
        "main-output"
      ],
      "DNSConfigurator": "vultr-dns"
    }
  ]
}

=== io7m-com/certusine/com.io7m.certusine.tests/src/test/resources/com/io7m/certusine/tests/configuration-basic.json
{
  "%Schema": "https://www.io7m.com/software/certusine/config-1.json",

  "Options": {
    "DNSWaitTime": "PT5M",
    "CertificateStore": "store.db",
    "CertificateExpirationThreshold": "PT72H"
  },

  "Accounts": [
    {
      "Name": "main",
      "PublicKeyPath": "fake.pub",
      "PrivateKeyPath": "fake.pri",
      "AcmeURI": "acme://localhost:20000/"
    }
  ],

  "Outputs": [
    {
      "Type": "directory",
      "Name": "main-output",
      "Parameters": [
        {
          "Name": "path",
          "Value": "/tmp"
        }
      ]
    }
  ],

  "DNSConfigurators": [
    {
      "Type": "vultr",
      "Name": "vultr-dns",
      "Parameters": [
        {
          "Name": "api-key",
          "Value": "abcd"
        },
        {
          "Name": "domain",
          "Value": "example.com"
        }
      ]
    }
  ],

  "Domains": [
    {
      "Name": "example.com",
      "Account": "main",
      "Certificates": [
        {
          "Name": "www",
          "PublicKeyPath": "fake.pub",
          "PrivateKeyPath": "fake.pri",
          "Hosts": [
            "www0.example.com",
            "www1.example.com",
            "www2.example.com"
          ]
        },
        {
          "Name": "mail",
          "PublicKeyPath": "fake.pub",
          "PrivateKeyPath": "fake.pri",
          "Hosts": [
            "mail0.example.com",
            "mail1.example.com"
          ]
        },
        {
          "Name": "wildcard",
          "PublicKeyPath": "fake.pub",
          "PrivateKeyPath": "fake.pri",
          "Hosts": [
            "*.example.com"
          ]
        }
      ],
      "Outputs": [
        "main-output"
      ],
      "DNSConfigurator": "vultr-dns"
    }
  ]
}
